---
kind: pipeline
name: ServerCore 1809 Images

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: build-base
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 1809
    context: base
    daemon_off: true
    dockerfile: base/Dockerfile.1809
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/base
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-scripts
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 1809
    build_args:
    - IMAGE_TAG=1809
    context: scripts
    daemon_off: true
    dockerfile: scripts/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/scripts
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-scm
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 1809
    build_args:
    - IMAGE_TAG=1809
    context: scm
    daemon_off: true
    dockerfile: scm/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/scm
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-tools
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 1809
    build_args:
    - IMAGE_TAG=1809
    context: tools
    daemon_off: true
    dockerfile: tools/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/tools
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-msbuild-2022
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 1809
    build_args:
    - IMAGE_TAG=1809
    context: msbuild-2022
    daemon_off: true
    dockerfile: msbuild-2022/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/msbuild-2022
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-buildbot-worker
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 1809
    build_args:
    - IMAGE_TAG=1809
    context: buildbot
    daemon_off: true
    dockerfile: buildbot/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/buildbot
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/**
  - refs/tags/**

---
kind: pipeline
name: ServerCore 2022 Images

platform:
  os: windows
  arch: amd64
  version: 2022

steps:
- name: build-base
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 2022
    context: base
    daemon_off: true
    dockerfile: base/Dockerfile.2022
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/base
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-scripts
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 2022
    build_args:
    - IMAGE_TAG=2022
    context: scripts
    daemon_off: true
    dockerfile: scripts/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/scripts
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-scm
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 2022
    build_args:
    - IMAGE_TAG=2022
    context: scm
    daemon_off: true
    dockerfile: scm/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/scm
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-tools
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 2022
    build_args:
    - IMAGE_TAG=2022
    context: tools
    daemon_off: true
    dockerfile: tools/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/tools
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-msbuild-2022
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 2022
    build_args:
    - IMAGE_TAG=2022
    context: msbuild-2022
    daemon_off: true
    dockerfile: msbuild-2022/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/msbuild-2022
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-buildbot-worker
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: 2022
    build_args:
    - IMAGE_TAG=2022
    context: buildbot
    daemon_off: true
    dockerfile: buildbot/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/buildbot
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/**
  - refs/tags/**

---
kind: pipeline
name: ServerCore AWS Images

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: build-base
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: aws
    context: base
    daemon_off: true
    dockerfile: base/Dockerfile.aws
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/base
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-scripts
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: aws
    build_args:
    - IMAGE_TAG=aws
    context: scripts
    daemon_off: true
    dockerfile: scripts/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/scripts
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-scm
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: aws
    build_args:
    - IMAGE_TAG=aws
    context: scm
    daemon_off: true
    dockerfile: scm/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/scm
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-tools
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: aws
    build_args:
    - IMAGE_TAG=aws
    context: tools
    daemon_off: true
    dockerfile: tools/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/tools
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-msbuild-aws
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: aws
    build_args:
    - IMAGE_TAG=aws
    context: msbuild-aws
    daemon_off: true
    dockerfile: msbuild-aws/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/msbuild-aws
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-buildbot-worker
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: aws
    build_args:
    - IMAGE_TAG=aws
    context: buildbot
    daemon_off: true
    dockerfile: buildbot/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/buildbot
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/**
  - refs/tags/**

---
kind: pipeline
name: Windows 1809 Images

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: build-base
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1809
    context: base
    daemon_off: true
    dockerfile: base/Dockerfile.windows-1809
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/base
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-scripts
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1809
    build_args:
    - IMAGE_TAG=windows-1809
    context: scripts
    daemon_off: true
    dockerfile: scripts/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/scripts
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-scm
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1809
    build_args:
    - IMAGE_TAG=windows-1809
    context: scm
    daemon_off: true
    dockerfile: scm/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/scm
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-tools
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1809
    build_args:
    - IMAGE_TAG=windows-1809
    context: tools
    daemon_off: true
    dockerfile: tools/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/tools
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-msbuild-windows-1809
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1809
    build_args:
    - IMAGE_TAG=windows-1809
    context: msbuild-windows-1809
    daemon_off: true
    dockerfile: msbuild-windows-1809/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/msbuild-windows-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-buildbot-worker
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1809
    build_args:
    - IMAGE_TAG=windows-1809
    context: buildbot
    daemon_off: true
    dockerfile: buildbot/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/buildbot
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/**
  - refs/tags/**

---
kind: pipeline
name: Windows AWS Images

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: build-base
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-aws
    context: base
    daemon_off: true
    dockerfile: base/Dockerfile.windows-aws
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/base
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-scripts
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-aws
    build_args:
    - IMAGE_TAG=windows-aws
    context: scripts
    daemon_off: true
    dockerfile: scripts/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/scripts
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-scm
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-aws
    build_args:
    - IMAGE_TAG=windows-aws
    context: scm
    daemon_off: true
    dockerfile: scm/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/scm
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-tools
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-aws
    build_args:
    - IMAGE_TAG=windows-aws
    context: tools
    daemon_off: true
    dockerfile: tools/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/tools
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-msbuild-windows-aws
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-aws
    build_args:
    - IMAGE_TAG=windows-aws
    context: msbuild-windows-aws
    daemon_off: true
    dockerfile: msbuild-windows-aws/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/msbuild-windows-aws
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

- name: build-buildbot-worker
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: windows-aws
    build_args:
    - IMAGE_TAG=windows-aws
    context: buildbot
    daemon_off: true
    dockerfile: buildbot/Dockerfile
    password:
      from_secret: docker_password
    purge: false
    repo: webkitdev/buildbot
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/**
  - refs/tags/**

---
kind: pipeline
name: Image Manifest

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: publish-manifest-base
  pull: always
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: base/manifest.tmpl
    username:
      from_secret: docker_username

- name: publish-manifest-scripts
  pull: always
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: scripts/manifest.tmpl
    username:
      from_secret: docker_username

- name: publish-manifest-scm
  pull: always
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: scm/manifest.tmpl
    username:
      from_secret: docker_username

- name: publish-manifest-tools
  pull: always
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: tools/manifest.tmpl
    username:
      from_secret: docker_username

- name: publish-manifest-msbuild-2022
  pull: always
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: msbuild-2022/manifest.tmpl
    username:
      from_secret: docker_username

- name: publish-manifest-buildbot-worker
  pull: always
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: buildbot/manifest.tmpl
    username:
      from_secret: docker_username

trigger:
  ref:
  - refs/heads/**
  - refs/tags/**

depends_on:
- ServerCore 1809 Images
- ServerCore 2022 Images
- ServerCore AWS Images
- Windows 1809 Images
- Windows AWS Images

...
