version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: Z4Z/soXtBPCQxnMStgrIfA==
  DOCKER_PASS:
    secure: EGhyu1peW00aBxbCXCyDCO8ybFgFk1MGtopq2d6GHDo=

install:
  - docker version

# Currently appveyor cannot support the size requirement for MSBuild
# See https://github.com/donny-dont/docker-webkit-dev/issues/2
build_script:
  - docker build -t webkitdev/scripts .\scripts\windowsservercore
  - docker build -t webkitdev/scm  .\scm\windowsservercore
  - docker build -t webkitdev/tools .\tools\windowsservercore
  - docker build -t webkitdev/msbuild .\msbuild\windowsservercore
  - docker build -t webkitdev/buildbot .\buildbot\windowsservercore

deploy_script:
  - docker login -u=%DOCKER_USER% -p=%DOCKER_PASS%
  - docker push webkitdev/scripts
  - docker push webkitdev/scm
  - docker push webkitdev/tools
  - docker push webkitdev/msbuild
  - docker push webkitdev/buildbot
