version: 1.0.{build}
image: Visual Studio 2017

install:
  - docker version

build_script:
  - ps: |
      [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
      (New-Object System.Net.WebClient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'get-pip.py');
  
