trigger:
- master

resources:
- repo: self

stages:
- stage: build_1809
  displayName: Build 1809 Image
  jobs:
  - job: build_1809_images
    displayName: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: Docker@2
      displayName: Build webkitdev/base:1809 image
      inputs:
        command: build
        repository: webkitdev/base
        dockerfile: '$(Build.SourcesDirectory)/base/Dockerfile.1809'
        buildContext: '$(Build.SourcesDirectory)/base'
        tags: |
          1809
    - task: Docker@2
      displayName: Build webkitdev/scripts:1809 image
      inputs:
        command: build
        repository: webkitdev/scripts
        dockerfile: '$(Build.SourcesDirectory)/scripts/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/scripts'
        arguments: --build-arg IMAGE_TAG=1809
        tags: |
          1809
    - task: Docker@2
      displayName: Build webkitdev/scm:1809 image
      inputs:
        command: build
        repository: webkitdev/scm
        dockerfile: '$(Build.SourcesDirectory)/scm/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/scm'
        arguments: --build-arg IMAGE_TAG=1809
        tags: |
          1809
    - task: Docker@2
      displayName: Build webkitdev/tools:1809 image
      inputs:
        command: build
        repository: webkitdev/tools
        dockerfile: '$(Build.SourcesDirectory)/tools/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/tools'
        arguments: --build-arg IMAGE_TAG=1809
        tags: |
          1809
    - task: Docker@2
      displayName: Build webkitdev/msbuild-2022:1809 image
      inputs:
        command: build
        repository: webkitdev/msbuild-2022
        dockerfile: '$(Build.SourcesDirectory)/msbuild-2022/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/msbuild-2022'
        arguments: --build-arg IMAGE_TAG=1809
        tags: |
          1809
    - task: Docker@2
      displayName: Build webkitdev/buildbot-worker:1809 image
      inputs:
        command: build
        repository: webkitdev/buildbot-worker
        dockerfile: '$(Build.SourcesDirectory)/buildbot-worker/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/buildbot-worker'
        arguments: --build-arg IMAGE_TAG=1809
        tags: |
          1809
    - task: Docker@2
      displayName: Build webkitdev/buildbot:1809 image
      inputs:
        command: build
        repository: webkitdev/buildbot
        dockerfile: '$(Build.SourcesDirectory)/buildbot/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/buildbot'
        arguments: --build-arg IMAGE_TAG=1809
        tags: |
          1809
