FROM webkitdev/tools

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

#--------------------------------------------------------------------
# Install MS Build Tools 2015
#--------------------------------------------------------------------

RUN Install-VSBuildTools2015;
