FROM mcr.microsoft.com/windows:1809@sha256:4e4fed5b12aa5bbe4982d2f183b7d006e40e2aa96c42f3eb1eabf1b29c62357e

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
