FROM mcr.microsoft.com/windows:1909@sha256:ff36545dfd662bac093537312f206329536e128ec6960c011008a96238706ce6

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
