FROM mcr.microsoft.com/windows:1809@sha256:04a42ae0f8250a0c301d3dccedb08b20d77a71eb6878c08740b3952332fcaa04

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
