FROM mcr.microsoft.com/windows:1909@sha256:7cc278a351086afb9efb8026a946aa6538c2f9bc9240cf29a8fb86717abc48ca

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
