FROM mcr.microsoft.com/windows:20H2@sha256:69d24bbbe5a2333030eaf27b58f9d3287fecd13d9680139afc0608dc634b328d

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
