FROM mcr.microsoft.com/windows/server:ltsc2022@sha256:d9362d78f9207f4421c36c641db35fb8070d46f2b06d8c05a33de17faeb86f56

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
