FROM mcr.microsoft.com/windows/server:ltsc2025@sha256:cc057bd91286601d395f3af0e0abe458a6ab64926cb40bded28afb200a69ce2f

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
