FROM mcr.microsoft.com/windows:20H2@sha256:963a54279b170d7160f3ba3e229ef03fc05a96ffdea2d927ca1238573d9f9402

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
