FROM mcr.microsoft.com/windows:1909@sha256:f4f8a46a98a13e26f97e1e2d400f19ff0b432f1f177ee7971dfe0faf4b6695e5

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
