FROM mcr.microsoft.com/windows/server:ltsc2025@sha256:1a0109f2bc32e262051fc0a0925ad3cc6cba24647f9b23acf459c1cc8a3af6cc

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
