FROM mcr.microsoft.com/windows/server:ltsc2022@sha256:7aee50db525cb853f70ac35c19ab0b37214d4f1b3e3549862f5a2d38167c6941

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
