FROM mcr.microsoft.com/windows/server:ltsc2022@sha256:6bf983c72b45dbf6f7958f719dd5fe9dd230edabe8d77eb932961b128c62b75b

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy -ExecutionPolicy RemoteSigned;
