name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build webkitdev/base
      uses: docker/build-push-action@v6
      with:
        push: false
        context: base
        file: Dockerfile.2022
        tags: webkitdev/base:2022
